name: list vars
on: workflow_dispatch
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - name: list all vars
      run: |
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
      shell: bash
      env:
        ALLMYSECRETS: ${{ toJSON(secrets) }}
        ALLMYVARS: ${{ toJSON(vars) }}
