name: list vars
on: push
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - name: list all vars
      run: |
          #echo "$ALLMYVARS" ${s:1:-1}
          echo "${ALLMYVARS:1:-1}" | sed "s/\"//g" | sed 's/,$//'
      shell: bash
      env:
        ALLMYVARS: ${{ toJSON(vars) }}
