name: list vars
on: push
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - name: list all vars
      run: |
        chmod +x scripts/testvars.sh
        ./scripts/testvars.sh test.tomb
      shell: bash
      env:
        ALLMYVARS: ${{ toJSON(vars) }}
