name: list vars
on: workflow_dispatch
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - name: list all vars
      run: |
          echo "$ALLMYVARS" | sed -e 's/^"//' -e 's/"$//'
      shell: bash
      env:
        ALLMYVARS: ${{ toJSON(vars) }}
