name: list vars
on: push
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: list all vars
      run: |
        chmod +x ./scripts/testvars.sh
        sh -x ./scripts/testvars.sh test.tomb
      shell: bash
      env:
        ALLMYVARS: ${{ toJSON(vars) }}
